SELECT
    --A.COLUMN_ID AS 字段序号,
    A.TABLE_NAME 表名,TT.comments 表说明,
    A.COLUMN_NAME AS 字段名,
    DECODE(E.UNIQUENESS, 'UNIQUE', 'Y', '') AS 主键,
    decode(A.DATA_TYPE,'VARCHAR2','varchar','DATE','datetime',lower(A.DATA_TYPE)) AS 类型,
    decode(A.DATA_TYPE,'DATE',23,A.DATA_LENGTH) 长度,
    --decode(A.DATA_PRECISION,null,'0',a.DATA_PRECISION) AS 整数位数,
    decode( A.DATA_SCALE,NULL,'0',a.DATA_SCALE) AS 小数位数,
    DECODE(A.NULLABLE, 'Y', 'Y', '') AS 允许空,
    A.DATA_DEFAULT AS 默认值,
    F.COMMENTS AS 字段描述
FROM USER_ALL_TABLES AA,
    USER_TAB_COLUMNS A,
    USER_COL_COMMENTS F,
    USER_TAB_COMMENTS TT,
    (SELECT B.TABLE_NAME,
            B.INDEX_NAME,
            B.UNIQUENESS,
            C.COLUMN_NAME,
            DECODE(D.CONSTRAINT_NAME, NULL, 'No', 'Yes') KEY
        FROM USER_INDEXES B,
            USER_IND_COLUMNS C,
            (SELECT CONSTRAINT_NAME
                FROM USER_CONSTRAINTS
                WHERE CONSTRAINT_TYPE = 'P') D
        WHERE B.INDEX_NAME = C.INDEX_NAME
        AND B.INDEX_NAME = D.CONSTRAINT_NAME(+)) E
WHERE
--a.table_name in ('PLT_SEARCHFIELD')
AA.TABLE_NAME = A.TABLE_NAME
AND A.TABLE_NAME = E.TABLE_NAME(+)
AND A.COLUMN_NAME = E.COLUMN_NAME(+)
AND A.TABLE_NAME = F.TABLE_NAME
AND A.COLUMN_NAME = F.COLUMN_NAME
AND AA.table_name=TT.table_name
-- AND AA.TABLE_NAME IN (__TABLE_NAME_LIST__) 
ORDER BY A.TABLE_NAME, A.COLUMN_ID;
